### PR TITLE
Add AmazonQLDB Data Provider

### PR DESCRIPTION
**Pull request by adrianiftode**
- build an AmazonQLDB Data Provider
- the limitation in this PR is to run the integration tests you need an AWS account as the tests run against one
- The restriction of this data provider is the Ledger database needs to be created; the tables are created on the fly, but there is an AWS limit of 20 tables

### CODE REVIEW

**Comment by thepirat000** [comment]
Looks like Amazon wants my credit card info if I want to test this, otherwise I cannot create a ledger. 

Unless there is a way to test this I won't be able to merge

**Comment by adrianiftode** [comment]
I can create an access key and a secret on my account for you.

**Comment by thepirat000** [comment]
oh, yes, that should work.

you can probably e-mail me the key

I've the same problem with DynamoDB. It worked the first months of my subscription.

**Comment by thepirat000** [comment]
Did the tests completed successfully on your local machine?

On my local the QLDB tests fails when targeting _netcoreapp2.0_ or _net461_ (they pass OK for _netcoreapp2.1_)

For **net461** I'm getting  `Digests don't match` exception:
Test_AmazonQLDB_HappyPath

```
Error Message:
   Amazon.QLDBSession.Model.BadRequestException : Digests don't match
  ----> Amazon.Runtime.Internal.HttpErrorResponseException : The remote server returned an error: (400) Bad Request.
  ----> System.Net.WebException : The remote server returned an error: (400) Bad Request.
  Stack Trace:
     at Amazon.QLDB.Driver.RetryHandler.RetriableExecute[T](Func`1 func, RetryPolicy retryPolicy, Action recoverAction, Action`1 retryAction)
   at Amazon.QLDB.Driver.SessionPool.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction)
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction)
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy)
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func)
   at Audit.NET.AmazonQLDB.Providers.AmazonQldbDataProvider.InsertEvent(AuditEvent auditEvent)
```
   
For **netcoreapp2.0** I get `Operation is not supported on this platform`:
Test_AmazonQLDB_HappyPath 
```
  Error Message:
   System.PlatformNotSupportedException : Operation is not supported on this platform.
  Stack Trace:
     at Amazon.QLDB.Driver.RetryHandler.RetriableExecute[T](Func`1 func, RetryPolicy retryPolicy, Action recoverAction, Action`1 retryAction)
   at Amazon.QLDB.Driver.SessionPool.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction)
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy)
   at Audit.NET.AmazonQLDB.Providers.AmazonQldbDataProvider.InsertEvent(AuditEvent auditEvent) in D:\MIOS\Proyectos .NET\Audit.NET\src\Audit.NET.AmazonQLDB\Providers\AmazonQldbDataProvider.cs:line 82
   at Audit.IntegrationTest.AmazonQldbDataProviderForTest.InsertEvent(AuditEvent auditEvent)   
```

**Comment by adrianiftode** [comment]
On my machine, I get only the digest issue on net461. I will check out your changes.
`RetriableExecute` comes from the AWS driver and I think it might happen only when they retry the operation, after an exception. I will try to reproduce. Thanks for checking, sorry I didn't check net461.

**Comment by adrianiftode** [comment]
I'm afraid the net461 problem is at the AmazonQLDB driver. I will raise an issue on their side.
If you also agree I can retarget this provider to netcoreapp2.0, netcoreapp2.1, and netcoreapp3.1 until the net461 issue is fixed.

I still couldn't reproduce the netcoreapp2.0 issue.

**Pull request merged**
