### PR TITLE
MQTT Data provider

### PR DESCRIPTION
**Pull request by davebown**
Hi not sure if you're interested in this or not but I thought i'd make a pull request anyway just on the off chance.

The only drawback is that the mqtt library i use isn't compatible with .NET 4.5 so that isn't a build target.

### CODE REVIEW

**Comment by thepirat000** [comment]
Awesome!
Can you include any kind of unit or integration test?

**Comment by davebown** [comment]
Hi give me a day or so I'll include an integration test. Didn't get chance to look at the test project yet. I also have another provider for Fluentd in the works and I can contribute that as well if you like.

**Comment by thepirat000** [comment]
yes of course. your work is welcome. regards.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davebown** [comment]
Yeah it will happen just a bit pressured with a deadline. May take me a little while longer.

**Comment by thepirat000** [comment]
no worries. thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
